// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var JSComponent = require("../../src/components/examples/JSComponent");

var make = JSComponent.default;

exports.make = make;
/* make Not a pure module */
